"""Initial migration: create all tables (fixed updated_at nullable)

Revision ID: 9f39b6e1449b
Revises: 
Create Date: 2025-12-07 22:01:53.389966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f39b6e1449b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名（唯一）'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱（唯一）'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='分类ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID（系统分类为NULL）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('type', sa.String(length=10), nullable=False, comment='分类类型（income/expense）'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标（Emoji或图标名称）'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='颜色代码（如#FF6B6B）'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预设分类'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_type'), 'categories', ['type'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False, comment='预算ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID（NULL表示总预算）'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='预算金额'),
    sa.Column('period_type', sa.String(length=20), nullable=False, comment='周期类型（monthly/yearly）'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='结束日期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_period', 'budgets', ['user_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False, comment='账目ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='金额'),
    sa.Column('type', sa.String(length=10), nullable=False, comment='类型（income/expense）'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='账目日期'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('tags', sa.String(length=255), nullable=True, comment='标签（逗号分隔）'),
    sa.Column('account_type', sa.String(length=50), nullable=True, comment='账户类型（现金/银行卡/支付宝/微信等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index('idx_user_type', 'transactions', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index('idx_user_type', table_name='transactions')
    op.drop_index('idx_user_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_index('idx_user_period', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_type'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
